/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor.pb-c.h"
void   bmp280_reading__init
                     (BMP280Reading         *message)
{
  static const BMP280Reading init_value = BMP280_READING__INIT;
  *message = init_value;
}
size_t bmp280_reading__get_packed_size
                     (const BMP280Reading *message)
{
  assert(message->base.descriptor == &bmp280_reading__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bmp280_reading__pack
                     (const BMP280Reading *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bmp280_reading__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bmp280_reading__pack_to_buffer
                     (const BMP280Reading *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bmp280_reading__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BMP280Reading *
       bmp280_reading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BMP280Reading *)
     protobuf_c_message_unpack (&bmp280_reading__descriptor,
                                allocator, len, data);
}
void   bmp280_reading__free_unpacked
                     (BMP280Reading *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bmp280_reading__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scd30_reading__init
                     (SCD30Reading         *message)
{
  static const SCD30Reading init_value = SCD30_READING__INIT;
  *message = init_value;
}
size_t scd30_reading__get_packed_size
                     (const SCD30Reading *message)
{
  assert(message->base.descriptor == &scd30_reading__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scd30_reading__pack
                     (const SCD30Reading *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scd30_reading__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scd30_reading__pack_to_buffer
                     (const SCD30Reading *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scd30_reading__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SCD30Reading *
       scd30_reading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SCD30Reading *)
     protobuf_c_message_unpack (&scd30_reading__descriptor,
                                allocator, len, data);
}
void   scd30_reading__free_unpacked
                     (SCD30Reading *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scd30_reading__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sgp30_reading__init
                     (SGP30Reading         *message)
{
  static const SGP30Reading init_value = SGP30_READING__INIT;
  *message = init_value;
}
size_t sgp30_reading__get_packed_size
                     (const SGP30Reading *message)
{
  assert(message->base.descriptor == &sgp30_reading__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sgp30_reading__pack
                     (const SGP30Reading *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sgp30_reading__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sgp30_reading__pack_to_buffer
                     (const SGP30Reading *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sgp30_reading__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SGP30Reading *
       sgp30_reading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SGP30Reading *)
     protobuf_c_message_unpack (&sgp30_reading__descriptor,
                                allocator, len, data);
}
void   sgp30_reading__free_unpacked
                     (SGP30Reading *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sgp30_reading__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smuart04_lreading__init
                     (SMUART04LReading         *message)
{
  static const SMUART04LReading init_value = SMUART04_LREADING__INIT;
  *message = init_value;
}
size_t smuart04_lreading__get_packed_size
                     (const SMUART04LReading *message)
{
  assert(message->base.descriptor == &smuart04_lreading__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smuart04_lreading__pack
                     (const SMUART04LReading *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smuart04_lreading__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smuart04_lreading__pack_to_buffer
                     (const SMUART04LReading *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smuart04_lreading__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SMUART04LReading *
       smuart04_lreading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SMUART04LReading *)
     protobuf_c_message_unpack (&smuart04_lreading__descriptor,
                                allocator, len, data);
}
void   smuart04_lreading__free_unpacked
                     (SMUART04LReading *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &smuart04_lreading__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor_update__init
                     (SensorUpdate         *message)
{
  static const SensorUpdate init_value = SENSOR_UPDATE__INIT;
  *message = init_value;
}
size_t sensor_update__get_packed_size
                     (const SensorUpdate *message)
{
  assert(message->base.descriptor == &sensor_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_update__pack
                     (const SensorUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_update__pack_to_buffer
                     (const SensorUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorUpdate *
       sensor_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorUpdate *)
     protobuf_c_message_unpack (&sensor_update__descriptor,
                                allocator, len, data);
}
void   sensor_update__free_unpacked
                     (SensorUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bmp280_reading__field_descriptors[2] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(BMP280Reading, has_temperature),
    offsetof(BMP280Reading, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(BMP280Reading, has_pressure),
    offsetof(BMP280Reading, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bmp280_reading__field_indices_by_name[] = {
  1,   /* field[1] = pressure */
  0,   /* field[0] = temperature */
};
static const ProtobufCIntRange bmp280_reading__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bmp280_reading__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BMP280Reading",
  "BMP280Reading",
  "BMP280Reading",
  "",
  sizeof(BMP280Reading),
  2,
  bmp280_reading__field_descriptors,
  bmp280_reading__field_indices_by_name,
  1,  bmp280_reading__number_ranges,
  (ProtobufCMessageInit) bmp280_reading__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scd30_reading__field_descriptors[3] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SCD30Reading, has_temperature),
    offsetof(SCD30Reading, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SCD30Reading, has_humidity),
    offsetof(SCD30Reading, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SCD30Reading, has_co2),
    offsetof(SCD30Reading, co2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scd30_reading__field_indices_by_name[] = {
  2,   /* field[2] = co2 */
  1,   /* field[1] = humidity */
  0,   /* field[0] = temperature */
};
static const ProtobufCIntRange scd30_reading__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scd30_reading__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SCD30Reading",
  "SCD30Reading",
  "SCD30Reading",
  "",
  sizeof(SCD30Reading),
  3,
  scd30_reading__field_descriptors,
  scd30_reading__field_indices_by_name,
  1,  scd30_reading__number_ranges,
  (ProtobufCMessageInit) scd30_reading__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sgp30_reading__field_descriptors[6] =
{
  {
    "co2",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_co2),
    offsetof(SGP30Reading, co2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tvoc",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_tvoc),
    offsetof(SGP30Reading, tvoc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baseline_co2",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_baseline_co2),
    offsetof(SGP30Reading, baseline_co2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baseline_tvoc",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_baseline_tvoc),
    offsetof(SGP30Reading, baseline_tvoc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h2",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_h2),
    offsetof(SGP30Reading, h2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ethanol",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SGP30Reading, has_ethanol),
    offsetof(SGP30Reading, ethanol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sgp30_reading__field_indices_by_name[] = {
  2,   /* field[2] = baseline_co2 */
  3,   /* field[3] = baseline_tvoc */
  0,   /* field[0] = co2 */
  5,   /* field[5] = ethanol */
  4,   /* field[4] = h2 */
  1,   /* field[1] = tvoc */
};
static const ProtobufCIntRange sgp30_reading__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sgp30_reading__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SGP30Reading",
  "SGP30Reading",
  "SGP30Reading",
  "",
  sizeof(SGP30Reading),
  6,
  sgp30_reading__field_descriptors,
  sgp30_reading__field_indices_by_name,
  1,  sgp30_reading__number_ranges,
  (ProtobufCMessageInit) sgp30_reading__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smuart04_lreading__field_descriptors[6] =
{
  {
    "pm10_smoke",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm10_smoke),
    offsetof(SMUART04LReading, pm10_smoke),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pm25_smoke",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm25_smoke),
    offsetof(SMUART04LReading, pm25_smoke),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pm100_smoke",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm100_smoke),
    offsetof(SMUART04LReading, pm100_smoke),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pm10_env",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm10_env),
    offsetof(SMUART04LReading, pm10_env),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pm25_env",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm25_env),
    offsetof(SMUART04LReading, pm25_env),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pm100_env",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SMUART04LReading, has_pm100_env),
    offsetof(SMUART04LReading, pm100_env),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smuart04_lreading__field_indices_by_name[] = {
  5,   /* field[5] = pm100_env */
  2,   /* field[2] = pm100_smoke */
  3,   /* field[3] = pm10_env */
  0,   /* field[0] = pm10_smoke */
  4,   /* field[4] = pm25_env */
  1,   /* field[1] = pm25_smoke */
};
static const ProtobufCIntRange smuart04_lreading__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor smuart04_lreading__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SMUART04LReading",
  "SMUART04LReading",
  "SMUART04LReading",
  "",
  sizeof(SMUART04LReading),
  6,
  smuart04_lreading__field_descriptors,
  smuart04_lreading__field_indices_by_name,
  1,  smuart04_lreading__number_ranges,
  (ProtobufCMessageInit) smuart04_lreading__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor_update__field_descriptors[5] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SensorUpdate, has_timestamp),
    offsetof(SensorUpdate, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bmp280",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorUpdate, bmp280),
    &bmp280_reading__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scd30",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorUpdate, scd30),
    &scd30_reading__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sgp30",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorUpdate, sgp30),
    &sgp30_reading__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "smuart04l",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorUpdate, smuart04l),
    &smuart04_lreading__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_update__field_indices_by_name[] = {
  1,   /* field[1] = bmp280 */
  2,   /* field[2] = scd30 */
  3,   /* field[3] = sgp30 */
  4,   /* field[4] = smuart04l */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange sensor_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sensor_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SensorUpdate",
  "SensorUpdate",
  "SensorUpdate",
  "",
  sizeof(SensorUpdate),
  5,
  sensor_update__field_descriptors,
  sensor_update__field_indices_by_name,
  1,  sensor_update__number_ranges,
  (ProtobufCMessageInit) sensor_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
